/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HienThi;

import DATABASE.PhanLoai;
import DATABASE.daoHOADON;
import Dialog.InHD;
import DoiTuong.HOADON;
import DoiTuong.LoaiRuou;
import DoiTuong.Ruou;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kero
 */
public class bangHOADON extends javax.swing.JFrame {

    /**
     * Creates new form bangHOADON
     */
    Vector Data = new Vector();
    Vector title = new Vector();
    DefaultTableModel Model;
    Vector tableData = new Vector();
    Vector tableTittle = new Vector();
    DefaultTableModel TblModel;
    
    public ArrayList<LoaiRuou> DSL = PhanLoai.getDSL();
    public ArrayList<HOADON> dsb = daoHOADON.getDSB();
    public bangHOADON() {
        initComponents();
          Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight() - 300) / 2);
        this.setLocation(x, y);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        bt_xoa.setEnabled(false);
        bt_sua.setEnabled(false);
        txt_ngayhd.setEnabled(false);
        txt_tongtien.setEnabled(true);
        dattieude();
        hienthidulieu();
        DatTenTieuDe();
        HienDuLieuLen();
    }
    public void dattieude(){
        title.add("Mã Hóa Đơn");
        title.add("Ngày Nhập");
        title.add("Mã Khách Hàng");
        title.add("Mã Nhân Viên");
        title.add("Tổng Tiền ");
        
    }
    public void hienthidulieu(){
        Data.removeAllElements();
        for(HOADON b : dsb){
            Vector v = new Vector();
            v.add(b.getMahd());
            v.add(b.getNgayhd());
            v.add(b.getMakh());
            v.add(b.getManv());
            v.add(b.getTongtien());
            Data.add(v);
            tblban.setModel(new DefaultTableModel(Data, title));
        }
        
    }
    public void DatTenTieuDe()
    {
        tableTittle.add("Mã loại sản phẩm");
        tableTittle.add("Tên loại sản phẩm");
        
    }
    public void HienDuLieuLen()
    {
        tableData.removeAllElements();
        for(LoaiRuou a : DSL)
        {
            Vector v = new Vector();
            v.add(a.getMaloai());
            v.add(a.getTenloai());
            tableData.add(v);
            tb_bang2.setModel(new DefaultTableModel(tableData,tableTittle));
        }
    }
    public void LayDuLieu(ArrayList<LoaiRuou> ds)
    {
        tableData.removeAllElements();
        for(LoaiRuou a : ds)
        {
            Vector v = new Vector();
            v.add(a.getMaloai());
            v.add(a.getTenloai());
            tableData.add(v);
            tb_bang2.setModel(new DefaultTableModel(tableData,tableTittle));
        }
    }
        public Boolean KiemTra(){
        if(txt_mahd.getText().equals("") || txt_makh.getText().equals("") || txt_manv.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không để trống", "Thông báo", 2);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_mahd = new javax.swing.JTextField();
        txt_ngayhd = new javax.swing.JTextField();
        txt_manv = new javax.swing.JTextField();
        txt_makh = new javax.swing.JTextField();
        txt_tongtien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblban = new javax.swing.JTable();
        bt_them = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        bt_sua = new javax.swing.JButton();
        bt_lammoi = new javax.swing.JButton();
        bt_cthd = new javax.swing.JButton();
        bt_cntt = new javax.swing.JButton();
        bt_inhd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_bang2 = new javax.swing.JTable();
        bt_tim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("HÓA ĐƠN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mã Hóa Đơn:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ngày Nhập:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Mã Nhân Viên:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mã Khách Hàng:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tổng Tiền:");

        txt_tongtien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tongtienKeyTyped(evt);
            }
        });

        tblban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblban);

        bt_them.setText("THÊM");
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });

        bt_xoa.setText("XÓA");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        bt_sua.setText("SỬA");
        bt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suaActionPerformed(evt);
            }
        });

        bt_lammoi.setText("LÀM MỚI");
        bt_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lammoiActionPerformed(evt);
            }
        });

        bt_cthd.setText("CHI TIẾT HÓA ĐƠN");
        bt_cthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cthdActionPerformed(evt);
            }
        });

        bt_cntt.setText("CẬP NHẬP TỔNG TIỀN");
        bt_cntt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cnttMouseClicked(evt);
            }
        });
        bt_cntt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cnttActionPerformed(evt);
            }
        });

        bt_inhd.setText("IN HÓA ĐƠN");
        bt_inhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inhdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Nhập tên KH:");

        tb_bang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_bang2);

        bt_tim.setText("Tìm");
        bt_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_ngayhd, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(bt_cntt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_cthd, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bt_inhd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_tim))
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_mahd))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ngayhd))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_manv))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_makh))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cthd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_cntt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(bt_inhd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbanMouseClicked
        int i = tblban.getSelectedRow();
        String mahd = tblban.getValueAt(i, 0).toString().trim();
        String ngayhd = tblban.getValueAt(i, 1).toString().trim();
        String makh = tblban.getValueAt(i, 2).toString().trim();
        String manv = tblban.getValueAt(i, 3).toString().trim();
        String tongtien = tblban.getValueAt(i, 4).toString().trim();
        txt_mahd.setText(mahd);
        txt_ngayhd.setText(ngayhd);
        txt_makh.setText(makh);
        txt_manv.setText(manv);
        txt_tongtien.setText(tongtien);
        bt_them.setEnabled(false);
        bt_xoa.setEnabled(true);
        bt_sua.setEnabled(true);
        txt_mahd.setEnabled(false);
        txt_ngayhd.setEnabled(false);
        txt_tongtien.setEnabled(true);
    }//GEN-LAST:event_tblbanMouseClicked

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        if(KiemTra()){
          if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION)== JOptionPane.YES_OPTION)
            {
                String sql = "insert into HOADON(mahd, ngayhd, makh, manv, tongtien) values ('"+txt_mahd.getText().trim()+"',GETDATE(),N'" + txt_makh.getText().trim()+ "',N'" + txt_manv.getText().trim()+ "',N'" + txt_tongtien.getText().trim()+"')";
                int kq = daoHOADON.ThemXoaSua(sql);
                if(kq != -1)
                {
                    dsb = daoHOADON.getDSB();
                    hienthidulieu();
                }
                else{
                          JOptionPane.showMessageDialog(this, "Mã đã tồn tại", "Thông báo", 2);
                     }
            }
         
        }
    }//GEN-LAST:event_bt_themActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        int i = tblban.getSelectedRow();
        
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION)== JOptionPane.YES_OPTION)
        {
            String sql = "delete from HOADON where mahd = '"+txt_mahd.getText().trim()+"'";
            if(daoHOADON.ThemXoaSua(sql)!=-1)
            {
                dsb = daoHOADON.getDSB();
                hienthidulieu();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng không thể xóa", "Thông báo", 2);
            }
        }
    }//GEN-LAST:event_bt_xoaActionPerformed

    private void bt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suaActionPerformed
        int cot = tblban.getSelectedRow();
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION)== JOptionPane.YES_OPTION)
        {
            String sql = "update HOADON set tencc = N'"+txt_ngayhd.getText().trim()+"' where mahd = '"+txt_mahd.getText().trim()+"'";
            int kq = daoHOADON.ThemXoaSua(sql);
            if(kq != 1)
            {
                dsb = daoHOADON.getDSB();
                hienthidulieu();
            }
             else
            {
                JOptionPane.showMessageDialog(this, "Không thể sửa", "Thông báo", 2);
            }
        }
       
    }//GEN-LAST:event_bt_suaActionPerformed

    private void bt_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lammoiActionPerformed
        bt_them.setEnabled(true);
        bt_xoa.setEnabled(false);
        bt_sua.setEnabled(false);
        txt_mahd.setEnabled(true);
        txt_manv.setEnabled(true);
        txt_makh.setEnabled(true);
        txt_tongtien.setEnabled(true);
        txt_mahd.setText(" ");
        txt_ngayhd.setText(" ");
        txt_makh.setText(" ");
        txt_manv.setText(" ");
        txt_tongtien.setText(" ");
    }//GEN-LAST:event_bt_lammoiActionPerformed

    private void bt_cnttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cnttActionPerformed

    }//GEN-LAST:event_bt_cnttActionPerformed

    private void bt_cthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cthdActionPerformed
        bangCTHOADON bcthd = new bangCTHOADON();
        bcthd.show();
    }//GEN-LAST:event_bt_cthdActionPerformed

    private void bt_inhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inhdActionPerformed
//        String sql = "select SUM(SOLUONG) as SoLan from CTHOADON where mahd like '"+txt_mahd.getText()+"' and maruou like '"+txt_maruou+"'";
        InHD in = new InHD(this, rootPaneCheckingEnabled);
        in.LayThongTin(txt_mahd.getText(), txt_makh.getText(), txt_manv.getText(),txt_ngayhd.getText(), Integer.parseInt(txt_tongtien.getText()));
        in.show();
        

    }//GEN-LAST:event_bt_inhdActionPerformed

    private void bt_cnttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cnttMouseClicked
       String sql = "update HOADON set TongTien = (select SUM(SOLUONG*GIABAN) from CTHOADON, RUOU where CTHOADON.MARUOU = RUOU.MARUOU and MAHD = p.MAHD) from HOADON p";
        int kq = daoHOADON.Update(sql);
        if (kq > 0){
                    
                    JOptionPane.showMessageDialog(this, "Cập nhật giá bán thành công !!");
                    hienthidulieu();
                   
                }else{
                    JOptionPane.showMessageDialog(this, "Cập nhật giá bán thất bại !!");
        }
    }//GEN-LAST:event_bt_cnttMouseClicked

    private void txt_tongtienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tongtienKeyTyped
         char c= evt.getKeyChar();
       if(c < '0' || c > '9')
           evt.consume();
    }//GEN-LAST:event_txt_tongtienKeyTyped

    private void bt_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timActionPerformed
        ArrayList<LoaiRuou> DS = new ArrayList<LoaiRuou>();
        DS = daoHOADON.TimTheoTen(txt_tenkh.getText());
        LayDuLieu(DS);
    }//GEN-LAST:event_bt_timActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bangHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bangHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bangHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bangHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bangHOADON().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cntt;
    private javax.swing.JButton bt_cthd;
    private javax.swing.JButton bt_inhd;
    private javax.swing.JButton bt_lammoi;
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_tim;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_bang2;
    private javax.swing.JTable tblban;
    private javax.swing.JTextField txt_mahd;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_ngayhd;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
