/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HienThi;

import DATABASE.PhanLoai;
import DoiTuong.LoaiRuou;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class HienThiLoaiRuou extends javax.swing.JFrame {
    Vector tableData = new Vector();
    Vector tableTittle = new Vector();
    DefaultTableModel TblModel;
    
    public ArrayList<LoaiRuou> DSL = PhanLoai.getDSL();
    public HienThiLoaiRuou() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight() - 300) / 2);
        this.setLocation(x, y);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         bt_xoa.setEnabled(false);
        bt_sua.setEnabled(false);
        DatTenTieuDe();
        HienDuLieuLen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_maloai = new javax.swing.JTextField();
        txt_tenloai = new javax.swing.JTextField();
        bt_them = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        bt_sua = new javax.swing.JButton();
        bt_thoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_bang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã Loại rượu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên Loại rượu");

        bt_them.setText("Thêm");
        bt_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_themMousePressed(evt);
            }
        });

        bt_xoa.setText("Xóa");
        bt_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_xoaMousePressed(evt);
            }
        });

        bt_sua.setText("Sửa");
        bt_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_suaMousePressed(evt);
            }
        });

        bt_thoat.setText("Thoát");
        bt_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_thoatMousePressed(evt);
            }
        });
        bt_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_thoatActionPerformed(evt);
            }
        });

        tb_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_bangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_bang);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("THÔNG TIN LOẠI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_them, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_thoat, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void DatTenTieuDe()
    {
        tableTittle.add("Mã loại sản phẩm");
        tableTittle.add("Tên loại sản phẩm");
        
    }
    public void HienDuLieuLen()
    {
        tableData.removeAllElements();
        for(LoaiRuou a : DSL)
        {
            Vector v = new Vector();
            v.add(a.getMaloai());
            v.add(a.getTenloai());
            tableData.add(v);
            tb_bang.setModel(new DefaultTableModel(tableData,tableTittle));
        }
    }
    public Boolean KiemTra(){
        if(txt_maloai.getText().equals("") || txt_tenloai.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui long khong de trong","Thong bao", 2);
            return false;
        }
        return true;
    }
    private void bt_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_thoatActionPerformed

    private void tb_bangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_bangMouseClicked
       int i = tb_bang.getSelectedRow();
        String maloai = tb_bang.getValueAt(i, 0).toString().trim();
        String tenloai = tb_bang.getValueAt(i, 1).toString().trim();
        txt_maloai.setText(maloai);
        txt_tenloai.setText(tenloai);
        bt_them.setEnabled(false);
        bt_xoa.setEnabled(true);
        bt_sua.setEnabled(true);
        txt_maloai.setEnabled(false);
    }//GEN-LAST:event_tb_bangMouseClicked

    private void bt_themMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_themMousePressed
        if(KiemTra()){
        if(JOptionPane.showConfirmDialog(this, "Ban co chac muon them khong ?", "Thông báo", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            String sql = " insert into loairuou(maloai,tenloai) values ('"+txt_maloai.getText().trim()+"', N'"+txt_tenloai.getText().trim()+"')";
            int kq = PhanLoai.ThemXoaSuaBan(sql);
            if(kq != -1)
            {
                DSL = PhanLoai.getDSL();
                HienDuLieuLen();
            }
               else
        {
            JOptionPane.showMessageDialog(this, "Ma da ton tai","Thong bao", 2);
        }
        }
        
       }
    }//GEN-LAST:event_bt_themMousePressed

    private void bt_xoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_xoaMousePressed
        int Row = tb_bang.getSelectedRow();
       if(JOptionPane.showConfirmDialog(this, "Ban co chac muon xoa khong ?", "Thông báo", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            String sql = "delete from loairuou where maloai = '"+txt_maloai.getText().trim()+"'";
            int kq = PhanLoai.ThemXoaSuaBan(sql);
            if(kq != -1)
            {
                DSL = PhanLoai.getDSL();
                HienDuLieuLen();
            }
            else
        {
            JOptionPane.showMessageDialog(this, "Khong the xoa","Thong bao", 2);
        }
                
        }
    }//GEN-LAST:event_bt_xoaMousePressed

    private void bt_suaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_suaMousePressed
        int Row = tb_bang.getSelectedRow();
       if(JOptionPane.showConfirmDialog(this, "Ban co chac muon sua khong ?", "Thông báo", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            String sql = "update ruou set tenloai = N'"+txt_tenloai.getText().trim()+"' where maloai = '"+txt_maloai.getText().trim()+"'";
            int kq = PhanLoai.ThemXoaSuaBan(sql);
            if(kq != -1)
            {
                DSL = PhanLoai.getDSL();
                HienDuLieuLen();
            }
             else
        {
            JOptionPane.showMessageDialog(this, "Khong the sua","Thong bao", 2);
        }
        }
    }//GEN-LAST:event_bt_suaMousePressed

    private void bt_thoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_thoatMousePressed
        // TODO add your handling code here:
        int tl = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ?", "Thông báo",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (tl == JOptionPane.NO_OPTION) return;
        else {
            this.dispose();
        }
    }//GEN-LAST:event_bt_thoatMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HienThiLoaiRuou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HienThiLoaiRuou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HienThiLoaiRuou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HienThiLoaiRuou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HienThiLoaiRuou().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_thoat;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_bang;
    private javax.swing.JTextField txt_maloai;
    private javax.swing.JTextField txt_tenloai;
    // End of variables declaration//GEN-END:variables
}
