/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HienThi;

import javax.swing.JOptionPane;


/**
 *
 * @author LENOVO
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);//--Hiển thị full màn hình
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);  
        Khoa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        nguoidung = new javax.swing.JMenu();
        DangNhap = new javax.swing.JMenuItem();
        DangXuat = new javax.swing.JMenuItem();
        ttruou = new javax.swing.JMenu();
        mn_loairuou = new javax.swing.JMenuItem();
        mn_ruou = new javax.swing.JMenuItem();
        banhang = new javax.swing.JMenu();
        HoaDon = new javax.swing.JMenuItem();
        NhaCungCap = new javax.swing.JMenuItem();
        qlnv = new javax.swing.JMenu();
        ThongTin = new javax.swing.JMenuItem();
        baocao = new javax.swing.JMenu();
        BaoCaoTheoNgay = new javax.swing.JMenuItem();
        BaoCaoTheoNgay1 = new javax.swing.JMenuItem();

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem14.setText("jMenuItem14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        nguoidung.setBackground(new java.awt.Color(255, 0, 0));
        nguoidung.setText("Người dùng");

        DangNhap.setText("Đăng nhập");
        DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangNhapActionPerformed(evt);
            }
        });
        nguoidung.add(DangNhap);

        DangXuat.setText("Đăng xuất");
        DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatActionPerformed(evt);
            }
        });
        nguoidung.add(DangXuat);

        jMenuBar1.add(nguoidung);

        ttruou.setText("Thông tin rượu");

        mn_loairuou.setText("Loại rượu");
        mn_loairuou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_loairuouActionPerformed(evt);
            }
        });
        ttruou.add(mn_loairuou);

        mn_ruou.setText("Các hãng rượu");
        mn_ruou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ruouActionPerformed(evt);
            }
        });
        ttruou.add(mn_ruou);

        jMenuBar1.add(ttruou);

        banhang.setText("Bán Hàng");

        HoaDon.setText("Hóa đơn bán");
        HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoaDonActionPerformed(evt);
            }
        });
        banhang.add(HoaDon);

        NhaCungCap.setText("Nhà cung cấp");
        NhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhaCungCapActionPerformed(evt);
            }
        });
        banhang.add(NhaCungCap);

        jMenuBar1.add(banhang);

        qlnv.setText("Quản lý nhân viên");

        ThongTin.setText("Thông tin nhân viên");
        ThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongTinActionPerformed(evt);
            }
        });
        qlnv.add(ThongTin);

        jMenuBar1.add(qlnv);

        baocao.setText("Báo cáo");

        BaoCaoTheoNgay.setText("Báo cáo theo ngày");
        BaoCaoTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaoCaoTheoNgayActionPerformed(evt);
            }
        });
        baocao.add(BaoCaoTheoNgay);

        BaoCaoTheoNgay1.setText("Báo cáo theo tháng");
        BaoCaoTheoNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaoCaoTheoNgay1ActionPerformed(evt);
            }
        });
        baocao.add(BaoCaoTheoNgay1);

        jMenuBar1.add(baocao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatActionPerformed
         int tl = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất ?", "Thông báo", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (tl == JOptionPane.NO_OPTION) return;
        else{
            JOptionPane.showMessageDialog(this, "Đã đăng xuất thành công !", "Thông báo",JOptionPane.INFORMATION_MESSAGE);
            DangXuat.setEnabled(false);
           
            ttruou.setEnabled(false);
            banhang.setEnabled(false);
            qlnv.setEnabled(false);
            DangNhap.setEnabled(true);
            mn_loairuou.setEnabled(false);
            mn_ruou.setEnabled(false);
            HoaDon.setEnabled(false);
            NhaCungCap.setEnabled(false);
            ThongTin.setEnabled(false);
            baocao.setEnabled(false);
           System.exit(0);
        }
       
    }//GEN-LAST:event_DangXuatActionPerformed

    private void mn_loairuouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_loairuouActionPerformed
       HienThiLoaiRuou frmttloaiRuou = new HienThiLoaiRuou();
        frmttloaiRuou.setVisible(true);
        this.DesktopPane.add(frmttloaiRuou);
        
    }//GEN-LAST:event_mn_loairuouActionPerformed

    private void mn_ruouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ruouActionPerformed
        HienThiRuou frmttRuou = new HienThiRuou();
        frmttRuou.setVisible(true);
        this.DesktopPane.add(frmttRuou);
    }//GEN-LAST:event_mn_ruouActionPerformed
    public void Khoa()
    {
        DangXuat.setEnabled(true);
          
            ttruou.setEnabled(true);
            banhang.setEnabled(true);
            qlnv.setEnabled(true);
            DangNhap.setEnabled(false);
            mn_loairuou.setEnabled(true);
            mn_ruou.setEnabled(true);
            HoaDon.setEnabled(true);
            NhaCungCap.setEnabled(true);
            ThongTin.setEnabled(true);
            baocao.setEnabled(true);
    }
    private void DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangNhapActionPerformed
       
    }//GEN-LAST:event_DangNhapActionPerformed

    private void ThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongTinActionPerformed
       QuanLiNhanVien frmQLNV = new QuanLiNhanVien();
       frmQLNV.setVisible(true);
        this.DesktopPane.add(frmQLNV);
    }//GEN-LAST:event_ThongTinActionPerformed

    private void HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoaDonActionPerformed
        bangHOADON frmhoadon = new bangHOADON();
        frmhoadon.setVisible(true);
         this.DesktopPane.add(frmhoadon);
    }//GEN-LAST:event_HoaDonActionPerformed

    private void NhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhaCungCapActionPerformed
        bangNCC frmncc = new bangNCC();
        frmncc.setVisible(true);
        this.DesktopPane.add(frmncc);
          
    }//GEN-LAST:event_NhaCungCapActionPerformed

    private void BaoCaoTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaoCaoTheoNgayActionPerformed
        BaoCaoTheoNgay frmBaoCao = new BaoCaoTheoNgay();
        frmBaoCao.setVisible(true);
        this.DesktopPane.add(frmBaoCao);
    }//GEN-LAST:event_BaoCaoTheoNgayActionPerformed

    private void BaoCaoTheoNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaoCaoTheoNgay1ActionPerformed
        BaoCaoTheoThang frmBaoCao = new BaoCaoTheoThang();
        frmBaoCao.setVisible(true);
        this.DesktopPane.add(frmBaoCao);
    }//GEN-LAST:event_BaoCaoTheoNgay1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BaoCaoTheoNgay;
    private javax.swing.JMenuItem BaoCaoTheoNgay1;
    private javax.swing.JMenuItem DangNhap;
    private javax.swing.JMenuItem DangXuat;
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem HoaDon;
    private javax.swing.JMenuItem NhaCungCap;
    private javax.swing.JMenuItem ThongTin;
    private javax.swing.JMenu banhang;
    private javax.swing.JMenu baocao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem mn_loairuou;
    private javax.swing.JMenuItem mn_ruou;
    private javax.swing.JMenu nguoidung;
    private javax.swing.JMenu qlnv;
    private javax.swing.JMenu ttruou;
    // End of variables declaration//GEN-END:variables
}
