/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HienThi;

import DATABASE.LayDSNV;
import DoiTuong.NhanVien;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class QuanLiNhanVien extends javax.swing.JFrame {
     Vector tableData = new Vector();
    Vector tableTittle = new Vector();
    DefaultTableModel TblModel;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy/mm/dd"); 
    /**
     * Creates new form QuanLiNhanVien
     */
    public ArrayList<NhanVien> DSNV = LayDSNV.getDSNV();
    public QuanLiNhanVien() {
        initComponents();
         Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight() - 300) / 2);
        this.setLocation(x, y);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        bt_xoa.setEnabled(false);
        bt_sua.setEnabled(false);
        DatTenTieuDe();
        HienDuLieuLen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_dktk = new javax.swing.JTextField();
        txt_dkmk = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ngaysinh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        bt_sua = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        bt_thoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_bang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));

        jLabel2.setText("Tài khoản");

        jLabel3.setText("Mật khẩu");

        txt_dkmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dkmkActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã nhân viên");

        jLabel5.setText("Họ và tên");

        jLabel6.setText("Ngày sinh");

        txt_ngaysinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ngaysinhFocusLost(evt);
            }
        });

        jLabel10.setText("Số điện thoại");

        txt_sdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sdtKeyTyped(evt);
            }
        });

        jLabel11.setText("Địa chỉ");

        bt_sua.setText("SỬA THÔNG TIN");
        bt_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_suaMousePressed(evt);
            }
        });

        bt_xoa.setText("XÓA NHÂN VIÊN");
        bt_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_xoaMousePressed(evt);
            }
        });

        bt_thoat.setText("THOÁT");
        bt_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_thoatMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_manv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(txt_hoten, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_diachi, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(txt_dktk, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_sdt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ngaysinh)
                        .addComponent(txt_dkmk, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_xoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_thoat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_sua, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(0, 132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_dktk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_dkmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(bt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(bt_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        tb_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_bangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_bang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void DatTenTieuDe()
    {
        tableTittle.add("Mã nhân viên");
        tableTittle.add("Tên nhân viên");
        tableTittle.add("Ngày sinh");
        tableTittle.add("Địa chỉ");
        tableTittle.add("Số điên thoại");
        tableTittle.add("Tài khoản");
        tableTittle.add("Mật khẩu");
    }
    public void HienDuLieuLen()
    {
        tableData.removeAllElements();
        for(NhanVien a : DSNV)
        {
            Vector v = new Vector();
            v.add(a.getMaNV());
           v.add(a.getTenNV());
           v.add(a.getNgaySinh());
           v.add(a.getDiaChi());
           v.add(a.getSDT());
           v.add(a.getTaiKhoan());
           v.add(a.getMatKhau());
           
            tableData.add(v);
            tb_bang.setModel(new DefaultTableModel(tableData,tableTittle));
        }
    }    public boolean KiemTra()
    {
        if(txt_dktk.getText().equals("") || txt_dkmk.getText().equals("") || txt_manv.getText().equals("") 
                 || txt_hoten.getText().equals("") || txt_ngaysinh.getText().equals("") || txt_diachi.getText().equals("") || txt_sdt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui long khong de trong","Thong bao", 2);
            return false;
        }
        return true;
    }
    private void tb_bangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_bangMouseClicked
                int i = tb_bang.getSelectedRow();
                String manv = tb_bang.getValueAt(i, 0).toString().trim();
                String tennv = tb_bang.getValueAt(i, 1).toString().trim();
                String ngaysinh = tb_bang.getValueAt(i, 2).toString().trim();
                String diachi = tb_bang.getValueAt(i, 3).toString().trim();
                String sdt = tb_bang.getValueAt(i, 4).toString().trim();
                String taikhoan = tb_bang.getValueAt(i, 5).toString().trim();
                String matkhau = tb_bang.getValueAt(i, 6).toString().trim();
                txt_manv.setText(manv);
                txt_hoten.setText(tennv);
                txt_ngaysinh.setText(ngaysinh);
                txt_diachi.setText(diachi);
                txt_sdt.setText(sdt);
                txt_dktk.setText(taikhoan);
                txt_dkmk.setText(matkhau);
                bt_xoa.setEnabled(true);
                bt_sua.setEnabled(true);
                txt_manv.setEnabled(false);
    }//GEN-LAST:event_tb_bangMouseClicked

    private void bt_xoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_xoaMousePressed
        int Row = tb_bang.getSelectedRow();
        if(JOptionPane.showConfirmDialog(this, "Ban co chac muon xoa khong ?", "Thông báo", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION) {
            String sql = "delete from NhanVien where manv = '"+txt_manv.getText().trim()+"'";
            int kq = LayDSNV.ThemXoaSuaBan(sql);
            if(kq != -1)
            {
                DSNV = LayDSNV.getDSNV();
                HienDuLieuLen();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Khong the xoa","Thong bao", 2);
            }

        }

    }//GEN-LAST:event_bt_xoaMousePressed

    private void bt_suaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_suaMousePressed
        int Row = tb_bang.getSelectedRow();
        if(JOptionPane.showConfirmDialog(this, "Ban co chac muon sua khong ?", "Thông báo", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION) {
            String sql = "update Nhanvien set tennv = N'"+txt_hoten.getText().trim()+"',ngsinh = '"+txt_ngaysinh.getText().trim()+"',"
            + "diachi = N'"+txt_diachi.getText().trim()+"',dthoai = '"+txt_sdt.getText().trim()+"',taikhoan = '"+txt_dktk.getText().trim()+"',matkhau ='"+txt_dkmk.getText().trim()+"' where manv = '"+txt_manv.getText().trim()+"'";
            int kq = LayDSNV.ThemXoaSuaBan(sql);
            if(kq != -1)
            {
                DSNV = LayDSNV.getDSNV();
                HienDuLieuLen();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Khong the sua","Thong bao", 2);
            }
        }
    }//GEN-LAST:event_bt_suaMousePressed

    private void txt_sdtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sdtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtKeyTyped

    private void txt_ngaysinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ngaysinhFocusLost
        try {
            sdf.parse(txt_ngaysinh.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày sai - yyyy / mm / dd");
            txt_ngaysinh.setText("");
        }
    }//GEN-LAST:event_txt_ngaysinhFocusLost

    private void txt_dkmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dkmkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dkmkActionPerformed

    private void bt_thoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_thoatMousePressed
         // TODO add your handling code here:
        int tl = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ?", "Thông báo",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (tl == JOptionPane.NO_OPTION) return;
        else {
            this.dispose();
        }
    }//GEN-LAST:event_bt_thoatMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_sua;
    private javax.swing.JButton bt_thoat;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_bang;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JPasswordField txt_dkmk;
    private javax.swing.JTextField txt_dktk;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    // End of variables declaration//GEN-END:variables
}
